In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.metrics import accuracy_score, classification_report
from imblearn.over_sampling import SMOTE
from sklearn import metrics
from sklearn.metrics import confusion_matrix
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier

Load our chosen dataest and view the first 5 rows

In [2]:
stroke_df = pd.read_csv("Stroke.csv")
stroke_df.head()

,id,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke
0,9046,Male,67.0,0,1,Yes,Private,Urban,228.69,36.6,formerly smoked,1
1,51676,Female,61.0,0,0,Yes,Self-employed,Rural,202.21,NaN,never smoked,1
2,31112,Male,80.0,0,1,Yes,Private,Rural,105.92,32.5,never smoked,1
3,60182,Female,49.0,0,0,Yes,Private,Urban,171.23,34.4,smokes,1
4,1665,Female,79.0,1,0,Yes,Self-employed,Rural,174.12,24.0,never smoked,1

Describe each column

In [3]:
stroke_df.describe()

,id,age,hypertension,heart_disease,avg_glucose_level,bmi,stroke
count,5110.000000,5110.000000,5110.000000,5110.000000,5110.000000,4909.000000,5110.000000
mean,36517.829354,43.226614,0.097456,0.054012,106.147677,28.893237,0.048728
std,21161.721625,22.612647,0.296607,0.226063,45.283560,7.854067,0.215320
min,67.000000,0.080000,0.000000,0.000000,55.120000,10.300000,0.000000
25%,17741.250000,25.000000,0.000000,0.000000,77.245000,23.500000,0.000000
50%,36932.000000,45.000000,0.000000,0.000000,91.885000,28.100000,0.000000
75%,54682.000000,61.000000,0.000000,0.000000,114.090000,33.100000,0.000000
max,72940.000000,82.000000,1.000000,1.000000,271.740000,97.600000,1.000000

Check which columns have null values

In [4]:
stroke_df.isnull().sum()

id                     0
gender                 0
age                    0
hypertension           0
heart_disease          0
ever_married           0
work_type              0
Residence_type         0
avg_glucose_level      0
bmi                  201
smoking_status         0
stroke                 0
dtype: int64

Use mean method to handle null values

In [5]:
numImputer = SimpleImputer(missing_values = np.nan, strategy='mean')
numImputer = numImputer.fit(stroke_df[['bmi']])
stroke_df.bmi = numImputer.transform(stroke_df[['bmi']])
stroke_df.head(60)

,id,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke
0,9046,Male,67.0,0,1,Yes,Private,Urban,228.69,36.600000,formerly smoked,1
1,51676,Female,61.0,0,0,Yes,Self-employed,Rural,202.21,28.893237,never smoked,1
2,31112,Male,80.0,0,1,Yes,Private,Rural,105.92,32.500000,never smoked,1
3,60182,Female,49.0,0,0,Yes,Private,Urban,171.23,34.400000,smokes,1
4,1665,Female,79.0,1,0,Yes,Self-employed,Rural,174.12,24.000000,never smoked,1
5,56669,Male,81.0,0,0,Yes,Private,Urban,186.21,29.000000,formerly smoked,1
6,53882,Male,74.0,1,1,Yes,Private,Rural,70.09,27.400000,never smoked,1
7,10434,Female,69.0,0,0,No,Private,Urban,94.39,22.800000,never smoked,1
8,27419,Female,59.0,0,0,Yes,Private,Rural,76.15,28.893237,Unknown,1
9,60491,Female,78.0,0,0,Yes,Private,Urban,58.57,24.200000,Unknown,1
10,12109,Female,81.0,1,0,Yes,Private,Rural,80.43,29.700000,never smoked,1
11,12095,Female,61.0,0,1,Yes,Govt_job,Rural,120.46,36.800000,smokes,1
12,12175,Female,54.0,0,0,Yes,Private,Urban,104.51,27.300000,smokes,1
13,8213,Male,78.0,0,1,Yes,Private,Urban,219.84,28.893237,Unknown,1
14,5317,Female,79.0,0,1,Yes,Private,Urban,214.09,28.200000,never smoked,1
15,58202,Female,50.0,1,0,Yes,Self-employed,Rural,167.41,30.900000,never smoked,1
16,56112,Male,64.0,0,1,Yes,Private,Urban,191.61,37.500000,smokes,1
17,34120,Male,75.0,1,0,Yes,Private,Urban,221.29,25.800000,smokes,1
18,27458,Female,60.0,0,0,No,Private,Urban,89.22,37.800000,never smoked,1
19,25226,Male,57.0,0,1,No,Govt_job,Urban,217.08,28.893237,Unknown,1
20,70630,Female,71.0,0,0,Yes,Govt_job,Rural,193.94,22.400000,smokes,1
21,13861,Female,52.0,1,0,Yes,Self-employed,Urban,233.29,48.900000,never smoked,1
22,68794,Female,79.0,0,0,Yes,Self-employed,Urban,228.70,26.600000,never smoked,1
23,64778,Male,82.0,0,1,Yes,Private,Rural,208.30,32.500000,Unknown,1
24,4219,Male,71.0,0,0,Yes,Private,Urban,102.87,27.200000,formerly smoked,1
25,70822,Male,80.0,0,0,Yes,Self-employed,Rural,104.12,23.500000,never smoked,1
26,38047,Female,65.0,0,0,Yes,Private,Rural,100.98,28.200000,formerly smoked,1
27,61843,Male,58.0,0,0,Yes,Private,Rural,189.84,28.893237,Unknown,1
28,54827,Male,69.0,0,1,Yes,Self-employed,Urban,195.23,28.300000,smokes,1
29,69160,Male,59.0,0,0,Yes,Private,Rural,211.78,28.893237,formerly smoked,1
30,43717,Male,57.0,1,0,Yes,Private,Urban,212.08,44.200000,smokes,1
31,33879,Male,42.0,0,0,Yes,Private,Rural,83.41,25.400000,Unknown,1
32,39373,Female,82.0,1,0,Yes,Self-employed,Urban,196.92,22.200000,never smoked,1
33,54401,Male,80.0,0,1,Yes,Self-employed,Urban,252.72,30.500000,formerly smoked,1
34,14248,Male,48.0,0,0,No,Govt_job,Urban,84.20,29.700000,never smoked,1
35,712,Female,82.0,1,1,No,Private,Rural,84.03,26.500000,formerly smoked,1
36,47269,Male,74.0,0,0,Yes,Private,Rural,219.72,33.700000,formerly smoked,1
37,24977,Female,72.0,1,0,Yes,Private,Rural,74.63,23.100000,formerly smoked,1
38,47306,Male,58.0,0,0,No,Private,Rural,92.62,32.000000,Unknown,1
39,62602,Female,49.0,0,0,Yes,Private,Urban,60.91,29.900000,never smoked,1
40,4651,Male,78.0,0,0,Yes,Private,Rural,78.03,23.900000,formerly smoked,1
41,1261,Male,54.0,0,0,Yes,Private,Urban,71.22,28.500000,never smoked,1
42,61960,Male,82.0,0,1,Yes,Private,Urban,144.90,26.400000,smokes,1
43,1845,Female,63.0,0,0,Yes,Private,Urban,90.90,28.893237,formerly smoked,1
44,7937,Male,60.0,1,0,Yes,Govt_job,Urban,213.03,20.200000,smokes,1
45,19824,Male,76.0,1,0,Yes,Private,Rural,243.58,33.600000,never smoked,1
46,37937,Female,75.0,0,1,No,Self-employed,Urban,109.78,28.893237,Unknown,1
47,47472,Female,58.0,0,0,Yes,Private,Urban,107.26,38.600000,formerly smoked,1
48,35626,Male,81.0,0,0,Yes,Self-employed,Urban,99.33,33.700000,never smoked,1
49,36338,Female,39.0,1,0,Yes,Private,Rural,58.09,39.200000,smokes,1
50,18587,Female,76.0,0,0,No,Private,Urban,89.96,28.893237,Unknown,1
51,15102,Male,78.0,1,0,Yes,Private,Urban,75.32,28.893237,formerly smoked,1
52,59190,Female,79.0,0,1,Yes,Private,Rural,127.29,27.700000,never smoked,1
53,47167,Female,77.0,1,0,Yes,Self-employed,Urban,124.13,31.400000,never smoked,1
54,8752,Female,63.0,0,0,Yes,Govt_job,Urban,197.54,28.893237,never smoked,1
55,25831,Male,63.0,0,1,Yes,Private,Rural,196.71,36.500000,formerly smoked,1
56,38829,Female,82.0,0,0,Yes,Private,Rural,59.32,33.200000,never smoked,1
57,66400,Male,78.0,0,0,Yes,Private,Urban,237.75,28.893237,formerly smoked,1
58,58631,Male,73.0,1,0,Yes,Self-employed,Urban,194.99,32.800000,never smoked,1
59,5111,Female,54.0,1,0,Yes,Govt_job,Urban,180.93,27.700000,never smoked,1

Drop Unknown and Other rows

In [6]:
stroke_df = stroke_df.replace(['Unknown'], [np.nan])
stroke_df = stroke_df.replace(['Other'], [np.nan])
stroke_df = stroke_df.dropna()
stroke_df.head(50)

,id,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke
0,9046,Male,67.0,0,1,Yes,Private,Urban,228.69,36.600000,formerly smoked,1
1,51676,Female,61.0,0,0,Yes,Self-employed,Rural,202.21,28.893237,never smoked,1
2,31112,Male,80.0,0,1,Yes,Private,Rural,105.92,32.500000,never smoked,1
3,60182,Female,49.0,0,0,Yes,Private,Urban,171.23,34.400000,smokes,1
4,1665,Female,79.0,1,0,Yes,Self-employed,Rural,174.12,24.000000,never smoked,1
5,56669,Male,81.0,0,0,Yes,Private,Urban,186.21,29.000000,formerly smoked,1
6,53882,Male,74.0,1,1,Yes,Private,Rural,70.09,27.400000,never smoked,1
7,10434,Female,69.0,0,0,No,Private,Urban,94.39,22.800000,never smoked,1
10,12109,Female,81.0,1,0,Yes,Private,Rural,80.43,29.700000,never smoked,1
11,12095,Female,61.0,0,1,Yes,Govt_job,Rural,120.46,36.800000,smokes,1
12,12175,Female,54.0,0,0,Yes,Private,Urban,104.51,27.300000,smokes,1
14,5317,Female,79.0,0,1,Yes,Private,Urban,214.09,28.200000,never smoked,1
15,58202,Female,50.0,1,0,Yes,Self-employed,Rural,167.41,30.900000,never smoked,1
16,56112,Male,64.0,0,1,Yes,Private,Urban,191.61,37.500000,smokes,1
17,34120,Male,75.0,1,0,Yes,Private,Urban,221.29,25.800000,smokes,1
18,27458,Female,60.0,0,0,No,Private,Urban,89.22,37.800000,never smoked,1
20,70630,Female,71.0,0,0,Yes,Govt_job,Rural,193.94,22.400000,smokes,1
21,13861,Female,52.0,1,0,Yes,Self-employed,Urban,233.29,48.900000,never smoked,1
22,68794,Female,79.0,0,0,Yes,Self-employed,Urban,228.70,26.600000,never smoked,1
24,4219,Male,71.0,0,0,Yes,Private,Urban,102.87,27.200000,formerly smoked,1
25,70822,Male,80.0,0,0,Yes,Self-employed,Rural,104.12,23.500000,never smoked,1
26,38047,Female,65.0,0,0,Yes,Private,Rural,100.98,28.200000,formerly smoked,1
28,54827,Male,69.0,0,1,Yes,Self-employed,Urban,195.23,28.300000,smokes,1
29,69160,Male,59.0,0,0,Yes,Private,Rural,211.78,28.893237,formerly smoked,1
30,43717,Male,57.0,1,0,Yes,Private,Urban,212.08,44.200000,smokes,1
32,39373,Female,82.0,1,0,Yes,Self-employed,Urban,196.92,22.200000,never smoked,1
33,54401,Male,80.0,0,1,Yes,Self-employed,Urban,252.72,30.500000,formerly smoked,1
34,14248,Male,48.0,0,0,No,Govt_job,Urban,84.20,29.700000,never smoked,1
35,712,Female,82.0,1,1,No,Private,Rural,84.03,26.500000,formerly smoked,1
36,47269,Male,74.0,0,0,Yes,Private,Rural,219.72,33.700000,formerly smoked,1
37,24977,Female,72.0,1,0,Yes,Private,Rural,74.63,23.100000,formerly smoked,1
39,62602,Female,49.0,0,0,Yes,Private,Urban,60.91,29.900000,never smoked,1
40,4651,Male,78.0,0,0,Yes,Private,Rural,78.03,23.900000,formerly smoked,1
41,1261,Male,54.0,0,0,Yes,Private,Urban,71.22,28.500000,never smoked,1
42,61960,Male,82.0,0,1,Yes,Private,Urban,144.90,26.400000,smokes,1
43,1845,Female,63.0,0,0,Yes,Private,Urban,90.90,28.893237,formerly smoked,1
44,7937,Male,60.0,1,0,Yes,Govt_job,Urban,213.03,20.200000,smokes,1
45,19824,Male,76.0,1,0,Yes,Private,Rural,243.58,33.600000,never smoked,1
47,47472,Female,58.0,0,0,Yes,Private,Urban,107.26,38.600000,formerly smoked,1
48,35626,Male,81.0,0,0,Yes,Self-employed,Urban,99.33,33.700000,never smoked,1
49,36338,Female,39.0,1,0,Yes,Private,Rural,58.09,39.200000,smokes,1
51,15102,Male,78.0,1,0,Yes,Private,Urban,75.32,28.893237,formerly smoked,1
52,59190,Female,79.0,0,1,Yes,Private,Rural,127.29,27.700000,never smoked,1
53,47167,Female,77.0,1,0,Yes,Self-employed,Urban,124.13,31.400000,never smoked,1
54,8752,Female,63.0,0,0,Yes,Govt_job,Urban,197.54,28.893237,never smoked,1
55,25831,Male,63.0,0,1,Yes,Private,Rural,196.71,36.500000,formerly smoked,1
56,38829,Female,82.0,0,0,Yes,Private,Rural,59.32,33.200000,never smoked,1
57,66400,Male,78.0,0,0,Yes,Private,Urban,237.75,28.893237,formerly smoked,1
58,58631,Male,73.0,1,0,Yes,Self-employed,Urban,194.99,32.800000,never smoked,1
59,5111,Female,54.0,1,0,Yes,Govt_job,Urban,180.93,27.700000,never smoked,1

Drop irrelevant columns

In [7]:
stroke_df = stroke_df.drop(['id'], axis=1)
stroke_df.head(50)

,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke
0,Male,67.0,0,1,Yes,Private,Urban,228.69,36.600000,formerly smoked,1
1,Female,61.0,0,0,Yes,Self-employed,Rural,202.21,28.893237,never smoked,1
2,Male,80.0,0,1,Yes,Private,Rural,105.92,32.500000,never smoked,1
3,Female,49.0,0,0,Yes,Private,Urban,171.23,34.400000,smokes,1
4,Female,79.0,1,0,Yes,Self-employed,Rural,174.12,24.000000,never smoked,1
5,Male,81.0,0,0,Yes,Private,Urban,186.21,29.000000,formerly smoked,1
6,Male,74.0,1,1,Yes,Private,Rural,70.09,27.400000,never smoked,1
7,Female,69.0,0,0,No,Private,Urban,94.39,22.800000,never smoked,1
10,Female,81.0,1,0,Yes,Private,Rural,80.43,29.700000,never smoked,1
11,Female,61.0,0,1,Yes,Govt_job,Rural,120.46,36.800000,smokes,1
12,Female,54.0,0,0,Yes,Private,Urban,104.51,27.300000,smokes,1
14,Female,79.0,0,1,Yes,Private,Urban,214.09,28.200000,never smoked,1
15,Female,50.0,1,0,Yes,Self-employed,Rural,167.41,30.900000,never smoked,1
16,Male,64.0,0,1,Yes,Private,Urban,191.61,37.500000,smokes,1
17,Male,75.0,1,0,Yes,Private,Urban,221.29,25.800000,smokes,1
18,Female,60.0,0,0,No,Private,Urban,89.22,37.800000,never smoked,1
20,Female,71.0,0,0,Yes,Govt_job,Rural,193.94,22.400000,smokes,1
21,Female,52.0,1,0,Yes,Self-employed,Urban,233.29,48.900000,never smoked,1
22,Female,79.0,0,0,Yes,Self-employed,Urban,228.70,26.600000,never smoked,1
24,Male,71.0,0,0,Yes,Private,Urban,102.87,27.200000,formerly smoked,1
25,Male,80.0,0,0,Yes,Self-employed,Rural,104.12,23.500000,never smoked,1
26,Female,65.0,0,0,Yes,Private,Rural,100.98,28.200000,formerly smoked,1
28,Male,69.0,0,1,Yes,Self-employed,Urban,195.23,28.300000,smokes,1
29,Male,59.0,0,0,Yes,Private,Rural,211.78,28.893237,formerly smoked,1
30,Male,57.0,1,0,Yes,Private,Urban,212.08,44.200000,smokes,1
32,Female,82.0,1,0,Yes,Self-employed,Urban,196.92,22.200000,never smoked,1
33,Male,80.0,0,1,Yes,Self-employed,Urban,252.72,30.500000,formerly smoked,1
34,Male,48.0,0,0,No,Govt_job,Urban,84.20,29.700000,never smoked,1
35,Female,82.0,1,1,No,Private,Rural,84.03,26.500000,formerly smoked,1
36,Male,74.0,0,0,Yes,Private,Rural,219.72,33.700000,formerly smoked,1
37,Female,72.0,1,0,Yes,Private,Rural,74.63,23.100000,formerly smoked,1
39,Female,49.0,0,0,Yes,Private,Urban,60.91,29.900000,never smoked,1
40,Male,78.0,0,0,Yes,Private,Rural,78.03,23.900000,formerly smoked,1
41,Male,54.0,0,0,Yes,Private,Urban,71.22,28.500000,never smoked,1
42,Male,82.0,0,1,Yes,Private,Urban,144.90,26.400000,smokes,1
43,Female,63.0,0,0,Yes,Private,Urban,90.90,28.893237,formerly smoked,1
44,Male,60.0,1,0,Yes,Govt_job,Urban,213.03,20.200000,smokes,1
45,Male,76.0,1,0,Yes,Private,Rural,243.58,33.600000,never smoked,1
47,Female,58.0,0,0,Yes,Private,Urban,107.26,38.600000,formerly smoked,1
48,Male,81.0,0,0,Yes,Self-employed,Urban,99.33,33.700000,never smoked,1
49,Female,39.0,1,0,Yes,Private,Rural,58.09,39.200000,smokes,1
51,Male,78.0,1,0,Yes,Private,Urban,75.32,28.893237,formerly smoked,1
52,Female,79.0,0,1,Yes,Private,Rural,127.29,27.700000,never smoked,1
53,Female,77.0,1,0,Yes,Self-employed,Urban,124.13,31.400000,never smoked,1
54,Female,63.0,0,0,Yes,Govt_job,Urban,197.54,28.893237,never smoked,1
55,Male,63.0,0,1,Yes,Private,Rural,196.71,36.500000,formerly smoked,1
56,Female,82.0,0,0,Yes,Private,Rural,59.32,33.200000,never smoked,1
57,Male,78.0,0,0,Yes,Private,Urban,237.75,28.893237,formerly smoked,1
58,Male,73.0,1,0,Yes,Self-employed,Urban,194.99,32.800000,never smoked,1
59,Female,54.0,1,0,Yes,Govt_job,Urban,180.93,27.700000,never smoked,1

In [8]:
stroke_df.gender = stroke_df.gender.replace(['Male','Female'], [0,1])
stroke_df.Residence_type = stroke_df.Residence_type.replace(['Urban','Rural'], [0,1])
stroke_df.ever_married = stroke_df.ever_married.replace(['Yes','No'], ['1','0'])
stroke_df.head()

,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke
0,0,67.0,0,1,1,Private,0,228.69,36.600000,formerly smoked,1
1,1,61.0,0,0,1,Self-employed,1,202.21,28.893237,never smoked,1
2,0,80.0,0,1,1,Private,1,105.92,32.500000,never smoked,1
3,1,49.0,0,0,1,Private,0,171.23,34.400000,smokes,1
4,1,79.0,1,0,1,Self-employed,1,174.12,24.000000,never smoked,1

In [9]:
X= stroke_df.drop('stroke', axis = 1)
Y= stroke_df.stroke

In [10]:
X

,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status
0,0,67.0,0,1,1,Private,0,228.69,36.600000,formerly smoked
1,1,61.0,0,0,1,Self-employed,1,202.21,28.893237,never smoked
2,0,80.0,0,1,1,Private,1,105.92,32.500000,never smoked
3,1,49.0,0,0,1,Private,0,171.23,34.400000,smokes
4,1,79.0,1,0,1,Self-employed,1,174.12,24.000000,never smoked
...,...,...,...,...,...,...,...,...,...,...
5102,1,57.0,0,0,1,Private,1,77.93,21.700000,never smoked
5105,1,80.0,1,0,1,Private,0,83.75,28.893237,never smoked
5106,1,81.0,0,0,1,Self-employed,0,125.20,40.000000,never smoked
5107,1,35.0,0,0,1,Self-employed,1,82.99,30.600000,never smoked
5108,0,51.0,0,0,1,Private,1,166.29,25.600000,formerly smoked

In [11]:
stroke_df.work_type.value_counts()

Private          2284
Self-employed     663
Govt_job          535
children           69
Never_worked       14
Name: work_type, dtype: int64

In [12]:
stroke_df.smoking_status.value_counts()

never smoked       1892
formerly smoked     884
smokes              789
Name: smoking_status, dtype: int64

In [13]:
labelencoder = LabelEncoder()

for col in X.columns:
    if X[col].dtype =='object':
        X[col] = labelencoder.fit_transform(X[col])

In [14]:
X

,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status
0,0,67.0,0,1,1,2,0,228.69,36.600000,0
1,1,61.0,0,0,1,3,1,202.21,28.893237,1
2,0,80.0,0,1,1,2,1,105.92,32.500000,1
3,1,49.0,0,0,1,2,0,171.23,34.400000,2
4,1,79.0,1,0,1,3,1,174.12,24.000000,1
...,...,...,...,...,...,...,...,...,...,...
5102,1,57.0,0,0,1,2,1,77.93,21.700000,1
5105,1,80.0,1,0,1,2,0,83.75,28.893237,1
5106,1,81.0,0,0,1,3,0,125.20,40.000000,1
5107,1,35.0,0,0,1,3,1,82.99,30.600000,1
5108,0,51.0,0,0,1,2,1,166.29,25.600000,0

Now that the data has been cleaned, split our data into train and test models

In [15]:
X_train, X_test, Y_train, Y_test = train_test_split(X,Y, test_size = 0.2, random_state = 42)

In [16]:
scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [17]:
Y.value_counts()

0    3363
1     202
Name: stroke, dtype: int64

Since the data is unbalanced with respect to the distribution of class labels, we employ SMOTE before classification

In [18]:
smote = SMOTE(random_state=42)
X_train_sm, Y_train_sm = smote.fit_resample(X_train_scaled, Y_train)

print("Number of samples after SMOTE:", len(X_train_sm), len(Y_train_sm))

Y_train_sm.value_counts()

Number of samples after SMOTE: 5400 5400

0    2700
1    2700
Name: stroke, dtype: int64

Begin Classification, firstly we evaluate the performance of a Decision Tree model

In [19]:
dt_classifier = DecisionTreeClassifier(random_state = 42)
dt_classifier.fit(X_train_sm, Y_train_sm)

DecisionTreeClassifier(random_state=42)

In [20]:
Y_pred_dt = dt_classifier.predict(X_test_scaled)
Y_pred_dt

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 0], dtype=int64)

Review and evaluate the performance of our Decision Tree model

In [21]:
acc = metrics.accuracy_score(Y_test, Y_pred_dt)
acc

0.8569424964936886

In [22]:
recall = metrics.recall_score(Y_test, Y_pred_dt)
recall

0.1

In [23]:
precision = metrics.precision_score(Y_test, Y_pred_dt)
precision

0.08064516129032258

In [24]:
f1 = metrics.f1_score(Y_test, Y_pred_dt)
f1

0.08928571428571427

In [25]:
cm = confusion_matrix(Y_test, Y_pred_dt)
cm

array([[606,  57],
       [ 45,   5]], dtype=int64)

In [26]:
print ('accuracy:%.2f\n\n'%(acc))
print('Confusion Matrix:')
print(cm, '\n\n')
print('-------------------------------------')
result = metrics.classification_report(Y_test, Y_pred_dt)
print('Classification Report: \n')
print(result)

accuracy:0.86


Confusion Matrix:
[[606  57]
 [ 45   5]]


-------------------------------------
Classification Report:

              precision    recall  f1-score   support

           0       0.93      0.91      0.92       663
           1       0.08      0.10      0.09        50

    accuracy                           0.86       713
   macro avg       0.51      0.51      0.51       713
weighted avg       0.87      0.86      0.86       713

Perform k-Nearest Neighbours classification

In [27]:
knn_classifier = KNeighborsClassifier(n_neighbors = 3)
knn_classifier.fit(X_train_sm, Y_train_sm)

KNeighborsClassifier(n_neighbors=3)

In [28]:
Y_pred_knn = knn_classifier.predict(X_test_scaled)

In [29]:
acc = metrics.accuracy_score(Y_test, Y_pred_knn)
acc

0.8288920056100981

In [30]:
recall = metrics.recall_score(Y_test, Y_pred_knn)
recall

0.14

In [31]:
precision = metrics.precision_score(Y_test, Y_pred_knn)
precision

0.08139534883720931

In [32]:
f1 = metrics.f1_score(Y_test, Y_pred_knn)
f1

0.10294117647058824

In [33]:
cm = confusion_matrix(Y_test, Y_pred_knn)
cm

array([[584,  79],
       [ 43,   7]], dtype=int64)

In [34]:
print ('accuracy:%.2f\n\n'%(acc))
print('Confusion Matrix:')
print(cm, '\n\n')
print('-------------------------------------')
result = metrics.classification_report(Y_test, Y_pred_knn)
print('Classification Report: \n')
print(result)

accuracy:0.83


Confusion Matrix:
[[584  79]
 [ 43   7]]


-------------------------------------
Classification Report:

              precision    recall  f1-score   support

           0       0.93      0.88      0.91       663
           1       0.08      0.14      0.10        50

    accuracy                           0.83       713
   macro avg       0.51      0.51      0.50       713
weighted avg       0.87      0.83      0.85       713